### ISSUE TITLE
How is this set up?

### ISSUE THREAD

**Issue by Sotorin** [VladShcherbin/phoenix-react#1]
This is not an issue, I just have some questions.
I really like how you separated client from the server but I can't figure out how you wired the webpack build from the client directory where all the JS files are and somehow they end up in proper directory on the server (in the server directory). How is this accomplished?

**Comment by VladShcherbin** [comment]
@Sotorin hey, I'm working with this setup like with a separate front/back-end.

I'm running a webpack dev server (port 3000) and phoenix server (port 4000) when developing the app. So, phoenix is just a backend api + websocket for my frontend.

When I need to do a release, I run npm script to compile js and css files and store them in the server directory.

I've also seen tutorials ([example](http://www.phoenixframework.org/docs/static-assets)) when webpack is used as a watcher, but I prefer to separate them so it's easy to switch parts if needed.

Feel free to ask questions if you'll have some.

**Comment by Sotorin** [comment]
@VladShcherbin,
Thanks for your help in this matter. I wanted to mimic your approach for some time (i.e. separating your front tend into another folder) but couldn't get it to work. Now, thanks to your example, I can do it.
